on:
  push:
    branches: [main]

name: Render and Publish
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - uses: quarto-dev/quarto-actions/setup@v2
      - uses: r-lib/actions/setup-r@v2
      - run: Rscript -e 'install.packages(c("rmarkdown", "knitr", "ggplot2", "dplyr", "plotDK", "httr2"))'
      - uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages